<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
  <html lang="en">
  <head>
    <title>Sitemap | Treadmill Reviews USA</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      * { box-sizing: border-box; }
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Inter', Segoe UI, Roboto, sans-serif;
        background: #f9fafb;
        color: #26282B;
        margin: 0;
        padding: 40px 20px;
      }
      .wrap { max-width: 960px; margin: 0 auto; }
      h1 { font-size: 1.75rem; font-weight: 900; margin: 0 0 4px; }
      .sub { color: #6b7280; margin: 0 0 28px; font-size: 0.95rem; }
      table {
        width: 100%;
        border-collapse: collapse;
        background: #fff;
        border: 1px solid #e5e7eb;
        border-radius: 12px;
        overflow: hidden;
        box-shadow: 0 1px 2px rgba(0,0,0,0.04);
      }
      thead th {
        text-align: left;
        font-size: 0.75rem;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        color: #6b7280;
        background: #f9fafb;
        padding: 14px 18px;
        border-bottom: 1px solid #e5e7eb;
      }
      tbody td {
        padding: 14px 18px;
        border-bottom: 1px solid #f0f1f3;
        font-size: 0.9rem;
        vertical-align: middle;
      }
      tbody tr:last-child td { border-bottom: none; }
      tbody tr:hover { background: #f9fafb; }
      a { color: #0F62FE; text-decoration: none; font-weight: 600; word-break: break-all; }
      a:hover { text-decoration: underline; }
      .badge {
        display: inline-block;
        padding: 2px 10px;
        border-radius: 999px;
        background: #FF5A1F1a;
        color: #FF5A1F;
        font-size: 0.75rem;
        font-weight: 700;
      }
      .count { color: #6b7280; font-size: 0.85rem; margin-bottom: 12px; }
      footer { margin-top: 24px; color: #9ca3af; font-size: 0.8rem; text-align: center; }
    </style>
  </head>
  <body>
    <div class="wrap">
      <h1>XML Sitemap</h1>
      <p class="sub">Treadmill Reviews USA &#8212; auto-generated, human-readable view</p>

      <xsl:choose>
        <xsl:when test="sitemap:sitemapindex">
          <p class="count"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemap file(s)</p>
          <table>
            <thead>
              <tr><th>Sitemap</th><th>Last Modified</th></tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                <tr>
                  <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                  <td><xsl:value-of select="sitemap:lastmod"/></td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </xsl:when>
        <xsl:otherwise>
          <p class="count"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URL(s)</p>
          <table>
            <thead>
              <tr><th>URL</th><th>Priority</th><th>Change Freq.</th><th>Last Modified</th></tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                  <td><span class="badge"><xsl:value-of select="sitemap:priority"/></span></td>
                  <td><xsl:value-of select="sitemap:changefreq"/></td>
                  <td><xsl:value-of select="sitemap:lastmod"/></td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </xsl:otherwise>
      </xsl:choose>

      <footer>Generated by @astrojs/sitemap &#183; treadmillreviewsusa.com</footer>
    </div>
  </body>
  </html>
</xsl:template>
</xsl:stylesheet>
